# Generated by Django 4.1.7 on 2023-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('artist', models.CharField(max_length=150)),
                ('album', models.CharField(max_length=150)),
                ('img_url', models.CharField(max_length=150)),
                ('duration', models.IntegerField()),
                ('song_id', models.CharField(max_length=150)),
            ],
        ),
    ]
