# Generated by Django 4.1.7 on 2023-03-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_track_album_uri_track_genres_track_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(to='spotify.genre'),
        ),
    ]
