# Generated by Django 4.1.7 on 2023-03-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_track_album_uri_track_genre_track_populatiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='genre',
            new_name='genres',
        ),
    ]
