# Generated by Django 4.1.7 on 2023-03-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_rename_genre_track_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='populatiry',
            new_name='popularity',
        ),
    ]
