# Generated by Django 4.1.7 on 2023-04-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_profile_url_userprofile_image_url'),
        ('spotify', '0005_remove_track_likes_like_track_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='listeners',
            field=models.ManyToManyField(related_name='listened_to_tracks', to='authentication.userprofile'),
        ),
    ]
