# Generated by Django 4.1.7 on 2023-03-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_rename_populatiry_track_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
