# Generated by Django 4.1.7 on 2023-05-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_track_listeners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(related_name='liked_tracks', to='spotify.like'),
        ),
    ]
