# Generated by Django 4.1.7 on 2023-03-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_track'),
        ('authentication', '0003_userprofile_spotifytoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='spotifyToken',
            new_name='spotify_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_tracks',
            field=models.ManyToManyField(related_name='profile', to='spotify.track'),
        ),
    ]
