# Generated by Django 4.1.7 on 2023-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_profile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_url',
            new_name='image_url',
        ),
    ]
