# Generated by Django 4.1.7 on 2023-05-03 04:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0016_remove_conversation_user_conversation_user_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowageInstance',
            new_name='SocialInstance',
        ),
    ]
