# Generated by Django 4.1.7 on 2023-05-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_alter_track_likes'),
        ('authentication', '0018_message_type_alter_conversation_user_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_tracks',
            field=models.ManyToManyField(related_name='profiles_of_likes', to='spotify.track'),
        ),
    ]
