# Generated by Django 4.1.7 on 2023-05-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_userprofile_auth_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_token',
        ),
    ]
